/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leetcode.java.general;


import java.util.Arrays;
import java.util.HashMap;

/*
https://leetcode.com/problems/decode-string/description/


 */
public class DecodeString {


    public static String decodeString(String s) {
        // will solve it by doing recursion

    }

    private static String returnedInnerValue(String s, int multiplier) {
        String[] chunks = s.split("\\[");


    }





    public static void main(String[] args) {
        String input = "3[a2[c]]";
        String returnedValues = decodeString(input);


    }
}
